// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1J8TlTq-1RGGxtEWcluwDfYsNOZwl68c',
    appId: '1:610453083826:web:a8f19c0f8e570eb2d21bab',
    messagingSenderId: '610453083826',
    projectId: 'roombooker-5e947',
    authDomain: 'roombooker-5e947.firebaseapp.com',
    storageBucket: 'roombooker-5e947.firebasestorage.app',
    measurementId: 'G-MBM4WWN4VJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMRSVQIL26ognzn5vwGe1O0JokZBFl_VQ',
    appId: '1:610453083826:ios:44cdd5026f0a5ad8d21bab',
    messagingSenderId: '610453083826',
    projectId: 'roombooker-5e947',
    storageBucket: 'roombooker-5e947.firebasestorage.app',
    iosClientId:
        '610453083826-m67onil0arc7o1k5agohf9eje4he2d4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomBooker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAny3qKV-m0yHye_OBYph8pR-ULhtJHEoQ',
    appId: '1:610453083826:android:6e7a6e6de92bd450d21bab',
    messagingSenderId: '610453083826',
    projectId: 'roombooker-5e947',
    storageBucket: 'roombooker-5e947.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1J8TlTq-1RGGxtEWcluwDfYsNOZwl68c',
    appId: '1:610453083826:web:4395811ae52fbd53d21bab',
    messagingSenderId: '610453083826',
    projectId: 'roombooker-5e947',
    authDomain: 'roombooker-5e947.firebaseapp.com',
    storageBucket: 'roombooker-5e947.firebasestorage.app',
    measurementId: 'G-ZPQWCHTBDQ',
  );
}
